global:
  scrape_interval: 10s

scrape_configs:
  - job_name: kitamon
    scrape_timeout: 8s
    metrics_path: /metrics

    static_configs:
      - targets:
        - 192.168.1.1
        - 192.168.1.2
        - 192.168.1.3

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target

      - source_labels: [__param_target]
        target_label: instance

      - target_label: __address__
        replacement: 127.0.0.1:4000
